archetypeDir           = "archetypes"
author                 = "admin"
baseUrl                = "https://trapesiepoesie.it"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "hugo-theme-pixyll-master"
themesDir              = "themes"
title                  = "trapesiepoesie"
enableEmoji            = true
DefaultContentLanguage = "en"
enableRobotsTXT        = true
#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

[Languages.ru]
weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post", "poesie", "ivostripezzi"]
  search_engine = true
  google_analytics_id = "G-NB9M61JD17"
  twitter_username = "username"
  paginate = 10
  blog_posts = true
  author    = "Alessandro Agugliaro"
  description = "Sito dedicato a poesia, narrativa, arte"
  # inserire immagine valida image = "/images/.jpg"

  [sitemap]
    changefreq = 'weekly'
    filename = 'search/sitemap.xml'
    priority = 0.5

  [markup.goldmark.renderer]
  unsafe= true

  # Scadenza cache per i file statici
  [params.headers]
    Cache-Control = "public, max-age=86400"
